# Generated by Django 4.0.3 on 2022-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordieTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordieid', models.EmailField(max_length=30)),
                ('task', models.CharField(max_length=30)),
            ],
        ),
    ]
