# Generated by Django 4.0.3 on 2022-03-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_coordieassignedtask_coordieid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordieassignedtask',
            name='taskCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
